includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml

batch_size: 16

data_root: ./core/data/miniImageNet--ravi
image_size: 84
workers: 16

way_num: 5
shot_num: 1
query_num: 16

test_episode: 200

classifier:
  name: DeepEMD_Pretrain
  kwargs:
    feat_dim: 640
    train_num_class: 64
    val_num_class: 16
    mode: meta
    args:
      way: 5
      shot: 1
      query: 16
      deepemd: fcn
      solver: opencv
      feature_pyramid: 5,2,1
      pretrain: nothing

backbone:
  name: resnet12emd
  kwargs: ~

epoch: 120

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: True

lr_scheduler:
  kwargs:
    gamma: 0.2
    step_size: 20
  name: StepLR
